// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC5KoBAiOOZC8_ucQseJVYYP0KhiI_etE',
    appId: '1:653104946293:web:574b4d3ea475fa79222c3c',
    messagingSenderId: '653104946293',
    projectId: 'smarthome-e2234',
    authDomain: 'smarthome-e2234.firebaseapp.com',
    storageBucket: 'smarthome-e2234.appspot.com',
    measurementId: 'G-3CDVZ0KE97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf2qPym8Gqp8fHy7PwvwY1LuHblqi_idI',
    appId: '1:653104946293:android:b46f34587f0dcd91222c3c',
    messagingSenderId: '653104946293',
    projectId: 'smarthome-e2234',
    storageBucket: 'smarthome-e2234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMgSnhUL-tLIGfQpYY_k4gaPi4CbITOW0',
    appId: '1:653104946293:ios:3269240d12100270222c3c',
    messagingSenderId: '653104946293',
    projectId: 'smarthome-e2234',
    storageBucket: 'smarthome-e2234.appspot.com',
    iosClientId: '653104946293-gjao9meh36bu26pu8a3i2fpg37qc3uf3.apps.googleusercontent.com',
    iosBundleId: 'com.penseapp.flutterfireSmarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMgSnhUL-tLIGfQpYY_k4gaPi4CbITOW0',
    appId: '1:653104946293:ios:3269240d12100270222c3c',
    messagingSenderId: '653104946293',
    projectId: 'smarthome-e2234',
    storageBucket: 'smarthome-e2234.appspot.com',
    iosClientId: '653104946293-gjao9meh36bu26pu8a3i2fpg37qc3uf3.apps.googleusercontent.com',
    iosBundleId: 'com.penseapp.flutterfireSmarthome',
  );
}
